language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t titatreb/docker-react-training -f Dockerfile.dev .

script:
  - docker run -e CI=true titatreb/docker-react-training npm run test